version: '3.8'

services:
  app:
    container_name: permitflow-take-home-exercise-backend
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/permitflowDb
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'